export const AUTH_REQ="AUTH_REQUEST";
export const AUTH_SUCCESS="AUTH_SUCCESS";
export const AUTH_FAILURE="AUTH_FAILUE";
export const RESETPWD_LEGIT="RESETPWD_LEGIT";
export const RESETPWD_FAILURE="RESETPWD_FAILURE";